In [5]:
import numpy as np
ar1=np.arange(13)
print(ar1)
len(ar1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


13

In [6]:
reshaped_array=ar1.reshape(13,1)
print(reshaped_array)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [7]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [9]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.identity(5,dtype=complex)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [12]:
ar1.shape

(13,)

In [16]:
ar2=np.arange(25).reshape(5,5)
print("\nOrginal array:")
print(ar2)
sub_arr=ar2[0:3,1:4]
print("\nSub-array:")
print(sub_arr)


Orginal array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Sub-array:
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [18]:
ar2[-4:-2,-4:-2]#negative indexing

array([[ 6,  7],
       [11, 12]])

In [19]:
ar2[1:4,1:4]#positive indexing

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [20]:
np.mean(ar2)

12.0

In [24]:
ar3=np.arange(50).reshape(5,10)
print(ar3)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [27]:
np.sum(ar3,axis=0)#to add based on column wise axis=0

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [28]:
np.sum(ar3,axis=1)#to add based on row wise axis=1

array([ 45, 145, 245, 345, 445])

In [29]:
np.sum(ar3)

1225

In [30]:
np.mean(ar3)#mean->average

24.5

In [31]:
np.median(ar3)

24.5

In [34]:
np.var(ar3)

208.25

In [35]:
np.std(ar3)

14.430869689661812

In [36]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [37]:
np.linspace(1,10,4,dtype=int)

array([ 1,  4,  7, 10])

In [38]:
np.linspace(12,30,12,retstep=True)

(array([12.        , 13.63636364, 15.27272727, 16.90909091, 18.54545455,
        20.18181818, 21.81818182, 23.45454545, 25.09090909, 26.72727273,
        28.36363636, 30.        ]),
 1.6363636363636365)

In [40]:
np.random.randint(40)

15

In [41]:
np.random.randint(20,30)

21

In [63]:
np.random.randint(4,6,2)

array([4, 5])

In [62]:
np.random.rand(4)

array([0.43582378, 0.19930196, 0.39736851, 0.96395822])

In [50]:
np.random.rand(3,4)

array([[0.76490468, 0.63176226, 0.53180527, 0.93474034],
       [0.99748067, 0.91625051, 0.09027046, 0.90333686],
       [0.2240338 , 0.2496321 , 0.45474487, 0.60182658]])

In [51]:
np.random.randn(5)

array([-1.51475316,  1.00680489,  0.0931687 , -0.86105056,  0.54489891])

In [52]:
np.random.randn(5,4)

array([[-0.59677303,  1.31030349, -0.70226283,  1.38364753],
       [-1.08550991,  0.57982949,  0.65592579,  0.64785658],
       [-0.96435911,  1.47234185,  0.34964689, -0.21731417],
       [ 1.18237746, -0.54019799,  1.2475425 , -0.35651828],
       [-0.30515339,  1.24214646, -1.94578198,  0.21214294]])

In [53]:
ar3.min()

0

In [54]:
ar3.max()

49

In [55]:
l1=[56,89,90,67,45]
print(l1.index(67))

3


In [56]:
print(ar3.tolist())

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [20, 21, 22, 23, 24, 25, 26, 27, 28, 29], [30, 31, 32, 33, 34, 35, 36, 37, 38, 39], [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]


In [59]:
print(ar3.argmin())
print(ar3.argmax())

0
49


In [60]:
l1=[56,89,90,67,45]
np1=np.array(l1)
print(np1.argmin())
print(np1.argmax())

4
2


In [64]:
np1

array([56, 89, 90, 67, 45])

In [65]:
np.sin(np1)
np.cos(np1)
np.tan(np1)

array([-0.61127369,  1.68582537, -1.99520041,  1.65231726,  1.61977519])

In [66]:
1/np.sin(np1)

array([-1.91735803,  1.16269686,  1.11857241, -1.16887977,  1.17522136])

In [67]:
np.cos(np1)/np.sin(np1)

array([-1.63592842,  0.59318125, -0.50120278,  0.60521065,  0.61736962])

In [70]:
#Task-1->write python code for the below logic
np2=np.array([1,2,3])
np3=np.array([4,5,6])
result=np.dot(np2,np3)
print(result)

32


In [72]:
fname=np.array(["sid","fn1","fn2"])
lname=np.array(["l","ln1","ln2"])
fname.tostring()

C:\Users\kedar\AppData\Local\Temp\ipykernel_8784\3275138043.py:3: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  fname.tostring()


b's\x00\x00\x00i\x00\x00\x00d\x00\x00\x00f\x00\x00\x00n\x00\x00\x001\x00\x00\x00f\x00\x00\x00n\x00\x00\x002\x00\x00\x00'

In [73]:
l=["Rahul","Shannu","Vinay"]
m=["q","ab","cd"]
c=l+m
print(c)

['Rahul', 'Shannu', 'Vinay', 'q', 'ab', 'cd']


In [1]:
import numpy as np
np2=np.array([1,2,3,8,3,5,9])
np3=np.array([4,5,6])
len1=len(np2)
len2=len(np3)
diff=abs(len1-len2)
for val in range(diff):
    np3=np.append(np3,1)
np.sum((np2*np3))

57

In [2]:
np1=np.array([1,34,56,78,np.nan,np.nan])
np1

array([ 1., 34., 56., 78., nan, nan])

In [82]:
np1[np.isnan(np1)]

array([nan, nan])

In [84]:
np1[~np.isnan(np1)]

array([ 1., 34., 56., 78.])

In [5]:
import pandas as pd
labels=['a','b','c']
my_data=[10,20,30]
arr=np.array(my_data)
d={'a':100,'b':200,'c':300}
pd.Series(my_data)

0    10
1    20
2    30
dtype: int64

In [6]:
type(pd.Series(my_data))

pandas.core.series.Series

In [7]:
pd.Series(data=my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [9]:
pd.Series(data=[print,sum,len])

0    <built-in function print>
1      <built-in function sum>
2      <built-in function len>
dtype: object

In [12]:
class profile:
    @property
    def display(self):
        print("My name is Rahul")
p=profile()
p.display

My name is Rahul


In [20]:
def decor(func):
    def inner():
        str1=func()
        return str1.upper()
    return inner
@decor
def greet():
    return "Good morning"
print(greet())

GOOD MORNING


In [22]:
ser1=pd.Series([1,2,3,4,5],["USA","India","Canada","UK","Egypt"])
print(ser1)

USA       1
India     2
Canada    3
UK        4
Egypt     5
dtype: int64


In [32]:
print(ser1[::-1])

UK        8
Canada    7
Brazil    6
USA       5
dtype: int64


In [33]:
print(ser1["UK"])
print(ser1[1])
print(ser1[0:3])

8
6
USA       5
Brazil    6
Canada    7
dtype: int64


In [34]:
ser1["China"]=9
ser1

USA       5
Brazil    6
Canada    7
UK        8
China     9
dtype: int64

In [35]:
ser1.drop("Brazil")

USA       5
Canada    7
UK        8
China     9
dtype: int64

In [37]:
ser1["China"]="duplicate"
ser1

USA               5
Brazil            6
Canada            7
UK                8
China     duplicate
dtype: object

In [38]:
df=pd.DataFrame(np.random.randn(5,4))
df

0         1         2         3
0 -0.451477  1.180398  0.221961  0.214084
1  0.753208  2.211794  0.285773 -0.659447
2 -0.669176 -0.549984  0.393077 -0.190629
3  0.977230 -0.322750  1.021102  2.444232
4 -1.157197  0.779756  1.832216  0.042305

In [56]:
df=pd.DataFrame(np.random.randn(5,4),['A','B','C','D','E'],['w','x','y','z'])
df

w         x         y         z
A -0.383107  0.387024  0.483384 -1.183667
B -0.977169 -0.071043 -0.679753 -1.588398
C  1.379355  0.840490 -0.458880 -0.803441
D  0.939636  0.988464  0.985537 -1.663983
E -1.136124 -1.198216  1.293858 -1.022079

In [43]:
d={"col1":[1,2],"col2":[3,4],"col3":[5,6]}
d

{'col1': [1, 2], 'col2': [3, 4], 'col3': [5, 6]}

In [45]:
df=pd.DataFrame(data=d)
df

col1  col2  col3
0     1     3     5
1     2     4     6

In [47]:
df=pd.DataFrame(d,["row1","row2"])
df

col1  col2  col3
row1     1     3     5
row2     2     4     6

In [49]:
df.index

Index(['row1', 'row2'], dtype='object')

In [52]:
df.T

row1  row2
col1     1     2
col2     3     4
col3     5     6

In [54]:
df

w         x         y         z
A -0.826361 -1.745097 -1.229056  1.439532
B -0.384647 -0.556991  1.040077  1.450739
C -0.897604 -0.230442 -0.275449 -1.440072
D -1.256663  0.678882  0.675278 -0.075815
E  0.280705 -0.857922  1.058450  0.535506

In [55]:
df.T

A         B         C         D         E
w -0.826361 -0.384647 -0.897604 -1.256663  0.280705
x -1.745097 -0.556991 -0.230442  0.678882 -0.857922
y -1.229056  1.040077 -0.275449  0.675278  1.058450
z  1.439532  1.450739 -1.440072 -0.075815  0.535506

In [57]:
type(df)

pandas.core.frame.DataFrame

In [58]:
df.columns

Index(['w', 'x', 'y', 'z'], dtype='object')

In [61]:
df.dtypes

w    float64
x    float64
y    float64
z    float64
dtype: object

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A to E
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   w       5 non-null      float64
 1   x       5 non-null      float64
 2   y       5 non-null      float64
 3   z       5 non-null      float64
dtypes: float64(4)
memory usage: 200.0+ bytes


In [63]:
df.axes

[Index(['A', 'B', 'C', 'D', 'E'], dtype='object'),
 Index(['w', 'x', 'y', 'z'], dtype='object')]

In [64]:
df.values

array([[-0.38310657,  0.3870245 ,  0.48338418, -1.18366679],
       [-0.97716944, -0.071043  , -0.67975329, -1.58839833],
       [ 1.37935457,  0.84049046, -0.45888016, -0.80344082],
       [ 0.93963577,  0.98846374,  0.98553678, -1.66398298],
       [-1.13612392, -1.19821648,  1.29385756, -1.02207875]])

In [65]:
df.ndim

2

In [66]:
df.size

20

In [70]:
df['w']

A   -0.383107
B   -0.977169
C    1.379355
D    0.939636
E   -1.136124
Name: w, dtype: float64

In [71]:
type(df['w'])

pandas.core.series.Series

In [73]:
df[['w','x','y']]

w         x         y
A -0.383107  0.387024  0.483384
B -0.977169 -0.071043 -0.679753
C  1.379355  0.840490 -0.458880
D  0.939636  0.988464  0.985537
E -1.136124 -1.198216  1.293858

In [75]:
df['new']=df['w']+df['y']
df

w         x         y         z       new
A -0.383107  0.387024  0.483384 -1.183667  0.100278
B -0.977169 -0.071043 -0.679753 -1.588398 -1.656923
C  1.379355  0.840490 -0.458880 -0.803441  0.920474
D  0.939636  0.988464  0.985537 -1.663983  1.925173
E -1.136124 -1.198216  1.293858 -1.022079  0.157734

In [77]:
df.drop('new',axis=1)

w         x         y         z
A -0.383107  0.387024  0.483384 -1.183667
B -0.977169 -0.071043 -0.679753 -1.588398
C  1.379355  0.840490 -0.458880 -0.803441
D  0.939636  0.988464  0.985537 -1.663983
E -1.136124 -1.198216  1.293858 -1.022079

In [78]:
df

w         x         y         z       new
A -0.383107  0.387024  0.483384 -1.183667  0.100278
B -0.977169 -0.071043 -0.679753 -1.588398 -1.656923
C  1.379355  0.840490 -0.458880 -0.803441  0.920474
D  0.939636  0.988464  0.985537 -1.663983  1.925173
E -1.136124 -1.198216  1.293858 -1.022079  0.157734

In [79]:
df.drop('new',axis=1,inplace=True)
df

w         x         y         z
A -0.383107  0.387024  0.483384 -1.183667
B -0.977169 -0.071043 -0.679753 -1.588398
C  1.379355  0.840490 -0.458880 -0.803441
D  0.939636  0.988464  0.985537 -1.663983
E -1.136124 -1.198216  1.293858 -1.022079